### ISSUE TITLE
What is opt folder? and please give instructions how to run the project

### ISSUE THREAD

**Issue by naveenspy111** [marcalcarazf/realtime-2D-to-3D-faces#1]

**Comment by marcalcarazf** [comment]
Opt folder is referenced inside **FileWalker.py** but is just used in the `__main__` function. **FileWalker.py** is just used by **FacialDataset.py**, so is never run standalone, so `__main__ `function is never executed and **opt** folder just references old code. I will delete it to avoid confusion.

About how to run the project, I added a lot of information inside **[Readme.md](https://github.com/marcalcarazf/realtime-2D-to-3D-faces/blob/master/README.md)**. All the general ideas are explained there, and in the disclaimers part you can find all the things that are not uploaded in the repository because different reasons (copyright, etc.).

If you have any doubt, please contact me here: marc.alcarazf@gmail.com.
